import authReducer from "./auth.reducer";

export default {
    REGISTER_START:"REGISTER_START",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_ERROR:"REGISTER_ERROR",

    LOGIN_START:"LOGIN_START",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_ERROR:"LOGIN_ERROR",
}