export default {
    GET_PRODUCT_START:"GET_PRODUCT_START",
    GET_PRODUCT_SUCCESS:"GET_PRODUCT_SUCCESS",
    GET_PRODUCT_ERROR:"GET_PRODUCT_ERROR",

    ADD_PRODUCT:"ADD_PRODUCT",
    DELETE_PRODUCT:"DELETE_PRODUCT",
}